---
title: "Timeline"
author: "Group C"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install package of ganttrify
# install.packages("remotes")
# remotes::install_github("giocomai/ganttrify")
library(tibble)
library(ganttrify)
```


```{r}
# create data.frame recipe_task
recipe_task <- tibble::tribble(
  ~wp, ~activity, ~start_date, ~end_date,
  "Gantt", "Timeline", "2023-12-01", "2023-12-04",
  "Description", "1.1 ReadME", "2023-12-01", "2023-12-20",
  "Description", "1.2 Project proposal", "2023-12-01", "2023-12-10",
  "Topic selection", "2.1 Data collection", "2023-12-01", "2023-12-04", 
  "Topic selection", "2.2 First meeting", "2023-12-03", "2023-12-04",
  "Data", "3.1 Data wrangling", "2023-12-05", "2023-12-08",
  "Shiny app", "4.1 Structure", "2023-12-06", "2023-12-09",
  "Shiny app", "4.2 Algorithm Design", "2023-12-08", "2023-12-12",
  "Shiny app", "4.3 Optimization", "2023-12-12", "2023-12-15",
  "Package", "5.1 Structure", "2023-12-10", "2023-12-14",
  "Package", "5.2 Function code", "2023-12-14", "2023-12-16",
  "Package", "5.3 Roxygen2", "2023-12-16", "2023-12-17",
  "Package", "5.4 Test", "2023-12-17", "2023-12-18",
  "Website", "6.1 Creation", "2023-12-18", "2023-12-20",
  "Slides", "7.1 Slides", "2023-12-18", "2023-12-20"
)


recipe_task_spots <- tibble::tribble(~activity, ~spot_type, ~spot_date,
                                         "Data visualisation", "O", "2020-10-30",
                                         "Writing", "O", "2020-10-31"
)


# recipe_task_spots <- tibble::tribble(~activity, ~spot_type, ~spot_date,
#                               "Timeline", "Zhiqi", "2023-12-03",    
#                               "1.1 ReadME", "D", "2023-12-10",
#                               "1.2 Project proposal", "E", "2023-12-05",
#                               "2.1 Data collection", "All", "2023-12-03",
#                               "2.2 First meeting", "All", "2023-12-03",
#                               "3.1 Data wrangling", "Sam", "2023-12-07",
#                               "4.1 Structure", "Sam", "2023-12-08",
#                               "4.2 Algorithm Design", "Sam", "2023-12-10",
#                               "4.3 Optimization", "D", "2023-12-14",
#                               "5.1 Structure", "D", "2023-12-12",
#                               "5.2 Function code", "D", "2023-12-15",
#                               "5.3 Roxygen2", "D", "2023-12-16",
#                               "5.4 Test", "D", "2023-12-17",
#                               "6.1 Creation", "Efthimis", "2023-12-18",
#                               "7.1 Slides", "Shuangfei", "2023-12-18",
#                               )
# 

```


```{r}
gantt_plot <- ganttrify(
  project = recipe_task,
  by_date = TRUE,
  exact_date = TRUE,
  size_wp = 5,
  size_activity = 3,
  line_end_wp = "round",
  line_end_activity = "butt",
  month_date_label = TRUE,
)
print(gantt_plot)
```



