---
title: "Miam miam"
output: html_document
date: "2023-12-04"
---

```{r, echo = FALSE, message = FALSE}

packages <- c(
  "knitr","plotly","dplyr","readr","shiny"


)

#purrr::walk(packages, library, character.only = TRUE)


opts_chunk$set(root.dir = '../Meal-sugestion/') 
```



```{r setup, include=FALSE}
recettes <- read.csv('food_recipes.csv')
```

```{r}
recettes <- na.omit(recettes)
```

```{r}
# Load the library
library(cld2)

# Redefine the is_english function with simplified logic
is_english <- function(text) {
  # Check for NA or empty string
  if (is.na(text) || text == "") {
    return(FALSE)
  }
  
  # Perform language detection with error handling
  tryCatch({
    lang_detection <- detect_language(text)
    # Simplify the check to just look for "en" in the detection
    return(lang_detection[[1]] == "en" || lang_detection == "en")
  }, error = function(e) {
    # If there's an error, assume it's not English
    return(FALSE)
  })
}

# Apply the updated function to each description
english_rows <- sapply(recettes$description, is_english)

# Log the number of English rows detected
cat("Number of English rows detected:", sum(english_rows), "\n")

# Filter rows
recettes <- recettes[english_rows, ]
```

```{r}
# Assuming df_clean is your cleaned dataframe

# Remove 'M' and convert to numeric for prep_time
recettes$prep_time <- as.numeric(gsub("M", "", recettes$prep_time))

# Remove 'M' and convert to numeric for cook_time
recettes$cook_time <- as.numeric(gsub("M", "", recettes$cook_time))


```

```{r}
# Convert the ingredients string to a list of ingredients
recettes$ingredients <- strsplit(recettes$ingredients, "\\|")
```


```{r}
recettes <- subset(recettes, select = -c(record_health, vote_count, author, tags,url))
```


```{r}
recettes$ingredients <- sapply(recettes$ingredients, function(x) paste(x, collapse = ", "))
write.csv(recettes, "recipes.csv", row.names = FALSE)

```




```{r}
#recipes <- read_csv("recipes.csv")
```


```{r}
#na_rows_count <- sum(complete.cases(recipes) == FALSE)
#na_rows_count
```


```{r}
#recipes <- na.omit(recipes)
```












